'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Regenerated from markup to restore missing/stale control declarations.
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _2021all

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''UCHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents UCHeader As Global.admintickets.UC_header

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Panel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents Panel2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''NewtxtName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents NewtxtName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''NewtxtEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents NewtxtEmail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''NewtxtDOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents NewtxtDOB As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''NewtxtAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents NewtxtAddress As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''NewtxtPostcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents NewtxtPostcode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''DDnewType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents DDnewType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDnewStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents DDnewStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''BnewSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents BnewSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtSearchTerm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents txtSearchTerm As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents BSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSearchall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents btnSearchall As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LBTotalrecordcount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBTotalrecordcount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBSearchrecordcount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBSearchrecordcount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents GridView1 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''LBSaleID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBSaleID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBTicketID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBTicketID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents txtName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''requiredname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents requiredname As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''LBemail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBemail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtemail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents txtemail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LBDOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBDOB As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents txtDOB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LBaddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBaddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtaddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents txtaddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''requiredaddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents requiredaddress As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''LBpostcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBpostcode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtpostcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents txtpostcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LBType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents DDType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''requiredDDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents requiredDDL As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''LBStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents DDStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''EditButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents EditButton As Global.System.Web.UI.WebControls.linkButton

    '''<summary>
    '''EditSaveButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents EditSaveButton As Global.System.Web.UI.WebControls.linkButton

    '''<summary>
    '''EditCancelButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents EditCancelButton As Global.System.Web.UI.WebControls.linkButton

    '''<summary>
    '''Footer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents Footer1 As Global.admintickets.UC_footer

End Class
