<%@ Page Language="vb" AutoEventWireup="true" CodeBehind="admin_walkup.aspx.vb" Inherits="admintickets.Admin_walkup" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Walk-Up Admin</title>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />


    <link href="css/jquery-ui.min.css" rel="stylesheet" />
     <style>

 .card-header {
    background-color: #E5EBF1!important;
}

 .checked-back {
     background-color: #c7eed1!important;
 }

 .sold-back {
     background-color : #e2f0fd!important;
 }

.text-75 {
    font-size: 75%!important;
}
.text-25x {
    font-size : 2.5rem;
}
.text-2x {
    font-size : 2rem;
}
.text-15x {
    font-size : 1.5rem;
}

body {
    background-color: #f2f8fe;
}
.border-thick {
    border-width : 15px!important;
}
         </style>

</head>
<body class="flex">
    <form id="form1" runat="server">


        <div class="container-fluid pt-4">
                        <div class="row">
                            <div class="col-12">
            <h2>QOS v Airdrie 7th September  2024</h2>
                                </div>


            </div>
           </div> <!--end of fluid container -->
        <div class="container ">

<div class="row d-flex  justify-content-between"> <!-- start of number row -->

        <div class="card">
            <div class="card-body">
                1
            </div>
            </div>
              <div class="card">
            <div class="card-body">
                2
            </div>
                  </div>
                    <div class="card">
            <div class="card-body">
              3
            </div>
                        </div>
                          <div class="card">
            <div class="card-body">
               4
            </div>
        </div>









</div> <!--end of number row -->



         


        </div> <!-- end of container -->










 

    </form>
      <!--Script references. 
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->


    <!--Reference the jQuery library. -->
    <script src="Scripts/jquery-3.4.1.min.js" ></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="Scripts/jquery-ui.min.js"></script>
   



  


    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.2.2.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <!--Add script to update the page and send messages.--> 
    <script type="text/javascript">
        
        $(function () {
            // Declare a proxy to reference the hub. 
            var chat = $.connection.chatHubticketco;
            // Create a function that the hub can call to broadcast messages.
            chat.client.broadcastMessage = function (TotalCheckedIn, WalkUpCheckedIn, OnlineCheckedIn, OnlineSold, SeasonTicketsCheckedIn, AwaySold, HomeSold, awaycheckedin, homecheckedin, BDS1CheckedIn, BDS2CheckedIn, BDS3CheckedIn, BDS4CheckedIn, BDS5CheckedIn, BDS7CheckedIn, BDS8CheckedIn, BDS9CheckedIn, OakbankCheckedIn, TerreglesCheckedIn, Alpha1CheckedIn, Alpha2CheckedIn, Alpha3CheckedIn, Alpha4CheckedIn, AlphaTS1, AlphaTS2, EncTS1, TerraceTS1, BDSTS1, BDSTS2, lastupdate, BDS6CheckedIn, HomeWalkUpCheckedIn, AwayWalkUpCheckedIn) {
                // Html encode display name and message. 
                var TotalCheckedIn = $('<div />').text(TotalCheckedIn).html();
                var WalkUpCheckedIn = $('<div />').text(WalkUpCheckedIn).html();
                var HomeWalkUpCheckedIn = $('<div />').text(HomeWalkUpCheckedIn).html();
                var AwayWalkUpCheckedIn = $('<div />').text(AwayWalkUpCheckedIn).html();

                var OnlineCheckedIn = $('<div />').text(OnlineCheckedIn).html();
                var OnlineSold = $('<div />').text(OnlineSold).html();
                var SeasonTicketsCheckedIn = $('<div />').text(SeasonTicketsCheckedIn).html();
                var awaycheckedin = $('<div />').text(awaycheckedin).html();
                var homecheckedin = $('<div />').text(homecheckedin).html();
                var awaysold = $('<div />').text(AwaySold).html();
                var homesold = $('<div />').text(HomeSold).html();
                var lastupdate = $('<div />').text(lastupdate).html();
                var BDS1CheckedIn = $('<div />').text(BDS1CheckedIn).html();
                var BDS2CheckedIn = $('<div />').text(BDS2CheckedIn).html();
                var BDS3CheckedIn = $('<div />').text(BDS3CheckedIn).html();
                var BDS4CheckedIn = $('<div />').text(BDS4CheckedIn).html();
                var BDS5CheckedIn = $('<div />').text(BDS5CheckedIn).html();
                var BDS6CheckedIn = $('<div />').text(BDS6CheckedIn).html();
                var BDS7CheckedIn = $('<div />').text(BDS7CheckedIn).html();
                var BDS8CheckedIn = $('<div />').text(BDS8CheckedIn).html();
                var BDS9CheckedIn = $('<div />').text(BDS9CheckedIn).html();
                var OakbankCheckedIn = $('<div />').text(OakbankCheckedIn).html();

                var TerreglesCheckedIn = $('<div />').text(TerreglesCheckedIn).html();

                var Alpha1CheckedIn = $('<div />').text(Alpha1CheckedIn).html();
                var Alpha2CheckedIn = $('<div />').text(Alpha2CheckedIn).html();
                var Alpha3CheckedIn = $('<div />').text(Alpha3CheckedIn).html();
                var Alpha4CheckedIn = $('<div />').text(Alpha4CheckedIn).html();

                var AlphaTS1 = $('<div />').text(AlphaTS1).html();
                var AlphaTS2 = $('<div />').text(AlphaTS2).html();
                var EncTS1 = $('<div />').text(EncTS1).html();
                var TerraceTS1 = $('<div />').text(TerraceTS1).html();
                var BDSTS1 = $('<div />').text(BDSTS1).html();
                var BDSTS2 = $('<div />').text(BDSTS2).html();

                var homewalkupsold = 0;
                var awaywalkupsold = 0;

                var totalhomesold = BigInt(homesold) + BigInt(homewalkupsold);
                var totalhomecheckedin = BigInt(homecheckedin) + BigInt(HomeWalkUpCheckedIn);

                var totalawaysold = BigInt(awaysold) + BigInt(awaywalkupsold);
                var totalawaycheckedin = BigInt(awaycheckedin) + BigInt(AwayWalkUpCheckedIn);



 $("#TotalCheckedIn").fadeTo(500, 0, function () {
                    $("#TotalCheckedIn").text(TotalCheckedIn)

                        .fadeTo(500, 1.0);
                });

                $("#lastupdate").fadeTo(500, 0, function () {
                    $("#lastupdate").text(lastupdate)

                        .fadeTo(500, 1.0);
                });

                 
                $("#WalkUpCheckedIn").text(WalkUpCheckedIn);
                $("#homewalkupcheckedin").text(HomeWalkUpCheckedIn);
                $("#awaywalkupcheckedin").text(AwayWalkUpCheckedIn);
                $("#OnlineCheckedIn").text(OnlineCheckedIn);
                $("#OnlineSold").text(OnlineSold);
                $("#SeasonTicketsCheckedIn").text(SeasonTicketsCheckedIn);
                $("#awaycheckedin").text(awaycheckedin);
                $("#homecheckedin").text(homecheckedin);
                $("#awaysold").text(awaysold);
                $("#homesold").text(homesold);
               
                $("#BDS1CheckedIn").text(BDS1CheckedIn);
                $("#BDS2CheckedIn").text(BDS2CheckedIn);
                $("#BDS3CheckedIn").text(BDS3CheckedIn);
                $("#BDS4CheckedIn").text(BDS4CheckedIn);
                $("#BDS5CheckedIn").text(BDS5CheckedIn);
                $("#BDS6CheckedIn").text(BDS6CheckedIn);
                $("#BDS7CheckedIn").text(BDS7CheckedIn);
                $("#BDS8CheckedIn").text(BDS8CheckedIn);
                $("#BDS9CheckedIn").text(BDS9CheckedIn);

                $("#OakbankCheckedIn").text(OakbankCheckedIn);

                $("#TerreglesCheckedIn").text(TerreglesCheckedIn);

                $("#Alpha1CheckedIn").text(Alpha1CheckedIn);
                $("#Alpha2CheckedIn").text(Alpha2CheckedIn);
                $("#Alpha3CheckedIn").text(Alpha3CheckedIn);
                $("#Alpha4CheckedIn").text(Alpha4CheckedIn);


                $("#AlphaTS1").text(AlphaTS1);
                $("#AlphaTS2").text(AlphaTS2);
                $("#EncTS1").text(EncTS1);
                $("#TerraceTS1").text(TerraceTS1);
                $("#BDSTS1").text(BDSTS1);
                $("#BDSTS2").text(BDSTS2);
                $("#totalhomesold").text(totalhomesold);
                $("#totalhomecheckedin").text(totalhomecheckedin);
                $("#totalawaysold").text(totalawaysold);
                $("#totalawaycheckedin").text(totalawaycheckedin);



                
            };


            //reconnect connection
            $.connection.hub.disconnected(function () {
                console.log("disconnected");
                setTimeout(function () {
                    $.connection.hub.start();
                }, 5000); // Restart connection after 5 seconds.
                console.log("reconnected");
            });

            $.connection.hub.start().fail(function () {
                console.log("disconnected");
                setTimeout(function () {
                    $.connection.hub.start();
                }, 5000); // Restart connection after 5 seconds.
                console.log("reconnected");
            });


           
            $.connection.hub.start().done(function () {




             
                ////////    // Call the Send method on the hub. 
                chat.server.populateDataTable('');



              
                });





             
                
                
           



             




           
        });

    </script>
  

</body>
</html>
