'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Regenerated from markup to restore missing/stale control declarations.
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ballot_entry

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''DDcardtype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents DDcardtype As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDarea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents DDarea As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDperfarea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents DDperfarea As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDhouseholdnumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents DDhouseholdnumber As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''fixtureid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents fixtureid As Global.System.Web.UI.HtmlControls.HtmlGenericControl

End Class
