'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Regenerated from markup to restore missing/stale control declarations.
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ballot_list

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''UCHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents UCHeader As Global.admintickets.UC_header

    '''<summary>
    '''totalentries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents totalentries As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Luncheckedcount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents Luncheckedcount As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Lcheckedcorrect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents Lcheckedcorrect As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Lcheckedincorrect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents Lcheckedincorrect As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Lselectedcount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents Lselectedcount As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Lnotselectedcount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents Lnotselectedcount As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Lallocatedcount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents Lallocatedcount As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Lmainallocatedcount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents Lmainallocatedcount As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Lterraceallocatedcount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents Lterraceallocatedcount As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Lexcludedcount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents Lexcludedcount As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Lseatpref control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents Lseatpref As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Lterracepref control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents Lterracepref As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Lnopref control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents Lnopref As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''PNlist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents PNlist As Global.System.Web.UI.WebControls.panel

    '''<summary>
    '''SeasonID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents SeasonID As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Footer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents Footer1 As Global.admintickets.UC_footer

End Class
