<%@ Page Language="vb" AutoEventWireup="true" CodeBehind="dash_control.aspx.vb" Inherits="admintickets.dash_control" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>TMS Main Stand</title>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />


    <link href="css/jquery-ui.min.css" rel="stylesheet" />
     <style>

 .card-header {
    background-color: #E5EBF1!important;
}

 .checked-back {
     background-color: #c7eed1!important;
 }

 .sold-back {
     background-color : #e2f0fd!important;
 }

.text-75 {
    font-size: 75%!important;
}
.text-25x {
    font-size : 2.5rem;
}
.text-2x {
    font-size : 2rem;
}
.text-15x {
    font-size : 1.5rem;
}
         </style>

</head>
<body class="flex">
    <form id="form1" runat="server">


        <div class="container pt-4">

                        <div class="row">
                <div class="col-12 text-right">
                    <h5 id="lastupdate">NP</h5>
                </div>
            </div>



            <div class="row pt-4">
                <div class="col-12">
                    <div class="form-group">
                        <label for="fixtureid">Enter Fixture ID</label>
                        <input id="fixtureid" class="form-control" type="text" placeholder="Fixture ID" />

                    </div>

                      <div class="form-group">
                        <label for="fixtureid">Enter Update Interval (secs)</label>
                        <input id="updateInterval" class="form-control" type="text" placeholder="Update Interval (secs)" />

                    </div>

                     <button id="btnstart" type="submit" class="btn btn-success">Start</button>
                    <button id="btnstop" type="submit" class="btn btn-danger">Stop</button>

                </div>
            </div>
           
                           <div class="row pt-4">
                <div class="col-12 text-right">
                    <h5 id="log">NP</h5>
                </div>
            </div>



        </div> <!-- end of container -->










 

    </form>
      <!--Script references. 
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->


    <!--Reference the jQuery library. -->
    <script src="Scripts/jquery-3.4.1.min.js" ></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="Scripts/jquery-ui.min.js"></script>
   



  


    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.2.2.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <!--Add script to update the page and send messages.--> 
    <script type="text/javascript">
        

        $(function () {
            // Declare a proxy to reference the hub. 
            var chat = $.connection.chatHubticketco;
            // Create a function that the hub can call to broadcast messages.
            chat.client.broadcastMessage = function (TotalCheckedIn, WalkUpCheckedIn, OnlineCheckedIn, OnlineSold, SeasonTicketsCheckedIn, AwaySold, HomeSold, awaycheckedin, homecheckedin, BDS1CheckedIn, BDS2CheckedIn, BDS3CheckedIn, BDS4CheckedIn, BDS5CheckedIn, BDS7CheckedIn, BDS8CheckedIn, BDS9CheckedIn, OakbankCheckedIn, TerreglesCheckedIn, Alpha1CheckedIn, Alpha2CheckedIn, Alpha3CheckedIn, Alpha4CheckedIn, AlphaTS1, AlphaTS2, EncTS1, TerraceTS1, BDSTS1, BDSTS2, lastupdate) {
                // Html encode display name and message. 
                //var TotalCheckedIn = $('<div />').text(TotalCheckedIn).html();
                //var WalkUpCheckedIn = $('<div />').text(WalkUpCheckedIn).html();
                //var OnlineCheckedIn = $('<div />').text(OnlineCheckedIn).html();
                //var OnlineSold = $('<div />').text(OnlineSold).html();
                //var SeasonTicketsCheckedIn = $('<div />').text(SeasonTicketsCheckedIn).html();
                //var awaycheckedin = $('<div />').text(awaycheckedin).html();
                //var homecheckedin = $('<div />').text(homecheckedin).html();
                var lastupdate = $('<div />').text(lastupdate).html();
                //var BDS1CheckedIn = $('<div />').text(BDS1CheckedIn).html();
                //var BDS2CheckedIn = $('<div />').text(BDS2CheckedIn).html();
                //var BDS3CheckedIn = $('<div />').text(BDS3CheckedIn).html();
                //var BDS4CheckedIn = $('<div />').text(BDS4CheckedIn).html();
                //var BDS5CheckedIn = $('<div />').text(BDS5CheckedIn).html();
                //var BDS7CheckedIn = $('<div />').text(BDS7CheckedIn).html();
                //var BDS8CheckedIn = $('<div />').text(BDS8CheckedIn).html();
                //var BDS9CheckedIn = $('<div />').text(BDS9CheckedIn).html();
                //var OakbankCheckedIn = $('<div />').text(OakbankCheckedIn).html();

                //var TerreglesCheckedIn = $('<div />').text(TerreglesCheckedIn).html();

                //var Alpha1CheckedIn = $('<div />').text(Alpha1CheckedIn).html();
                //var Alpha2CheckedIn = $('<div />').text(Alpha2CheckedIn).html();
                //var Alpha3CheckedIn = $('<div />').text(Alpha3CheckedIn).html();
                //var Alpha4CheckedIn = $('<div />').text(Alpha4CheckedIn).html();


                //$("#TotalCheckedIn").text(TotalCheckedIn);
                //$("#WalkUpCheckedIn").text(WalkUpCheckedIn);
                //$("#OnlineCheckedIn").text(OnlineCheckedIn);
                //$("#OnlineSold").text(OnlineSold);
                //$("#SeasonTicketsCheckedIn").text(SeasonTicketsCheckedIn);
                //$("#awaycheckedin").text(awaycheckedin);
                //$("#homecheckedin").text(homecheckedin);
                $("#lastupdate").text(lastupdate);
                //$("#BDS1CheckedIn").text(BDS1CheckedIn);
                //$("#BDS2CheckedIn").text(BDS2CheckedIn);
                //$("#BDS3CheckedIn").text(BDS3CheckedIn);
                //$("#BDS4CheckedIn").text(BDS4CheckedIn);
                //$("#BDS5CheckedIn").text(BDS5CheckedIn);
                //$("#BDS7CheckedIn").text(BDS7CheckedIn);
                //$("#BDS8CheckedIn").text(BDS8CheckedIn);
                //$("#BDS9CheckedIn").text(BDS9CheckedIn);

                //$("#OakbankCheckedIn").text(OakbankCheckedIn);

                //$("#TerreglesCheckedIn").text(TerreglesCheckedIn);

                //$("#Alpha1CheckedIn").text(Alpha1CheckedIn);
                //$("#Alpha2CheckedIn").text(Alpha2CheckedIn);
                //$("#Alpha3CheckedIn").text(Alpha3CheckedIn);
                //$("#Alpha4CheckedIn").text(Alpha4CheckedIn);
            };


            ////reconnect connection
            //$.connection.hub.disconnected(function () {
            //    console.log("disconnected");
            //    setTimeout(function () {
            //        $.connection.hub.start();
            //    }, 5000); // Restart connection after 5 seconds.
            //    console.log("reconnected");
            //});

            //$.connection.hub.start().fail(function () {
            //    console.log("disconnected");
            //    setTimeout(function () {
            //        $.connection.hub.start();
            //    }, 5000); // Restart connection after 5 seconds.
            //    console.log("reconnected");
            //});


            setTimeout(function () {
            $.connection.hub.start().done(function () {
                ////////$('#sendmessage').click(function () {
                ////////    // Call the Send method on the hub. 
                
                ////////    // Clear text box and reset focus for next comment. 
                ////////    $('#message').val('').focus();
                ////////});

                // Start now tells the SERVER to run its own poll loop
                // (API import + broadcast) for this fixture. Once started the
                // loop lives in the web app, so this browser tab can be closed.
                $("#btnstart").click(function (event) {
                    event.stopPropagation();
                    event.stopImmediatePropagation();
                    event.preventDefault();

                    var fixtureId = $.trim($("#fixtureid").val());
                    var interval = parseInt($("#updateInterval").val(), 10) || 30;

                    if (!fixtureId) {
                        $("#log").text("Enter a Fixture ID first.");
                        return;
                    }

                    chat.server.startPolling(fixtureId, interval)
                        .done(function () {
                            $("#log").text("Server polling started for fixture " + fixtureId + " every " + interval + "s.");
                        })
                        .fail(function (e) {
                            $("#log").text("Start failed: " + e);
                        });
                });

                $("#btnstop").click(function (event) {
                    event.stopPropagation();
                    event.stopImmediatePropagation();
                    event.preventDefault();

                    chat.server.stopPolling()
                        .done(function () {
                            $("#log").text("Server polling stopped.");
                        })
                        .fail(function (e) {
                            $("#log").text("Stop failed: " + e);
                        });
                });


              
            });

   $.connection.hub.start().done(function () {

            ////////    // Call the Send method on the hub. 
       chat.server.populateDataTable('');



        });


            }, 5000);






                       
        });

     
    </script>
  

</body>
</html>
