'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Regenerated from markup to restore missing/stale control declarations.
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _default

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''UCHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents UCHeader As Global.admintickets.UC_header

    '''<summary>
    '''LBTotalAdultSold control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBTotalAdultSold As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBTotalConcSold control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBTotalConcSold As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBTotalJBSold control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBTotalJBSold As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBTotalOtherSold control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBTotalOtherSold As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBTotalTotalSold control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBTotalTotalSold As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBTotalPending control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBTotalPending As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBTotalShirtDraw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBTotalShirtDraw As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBTotalProv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBTotalProv As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBlastupdated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBlastupdated As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBTotalMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBTotalMain As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBTotalNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBTotalNew As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBTotalTerrace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBTotalTerrace As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBMainAdult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBMainAdult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBMainConc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBMainConc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBMainJB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBMainJB As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBMainOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBMainOther As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBNewAdult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBNewAdult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBNewConc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBNewConc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBNewJB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBNewJB As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBNewOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBNewOther As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBTerrAdult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBTerrAdult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBTerrConc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBTerrConc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBTerrJB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBTerrJB As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBTerrOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBTerrOther As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Footer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents Footer1 As Global.admintickets.UC_footer

End Class
