'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Regenerated from markup to restore missing/stale control declarations.
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class export_emails

    '''<summary>
    '''form2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents form2 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''btnUpdateSections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents btnUpdateSections As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LBupdatesections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBupdatesections As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnLoadSuccesful control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents btnLoadSuccesful As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnLoadBDSH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents btnLoadBDSH As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnLoadBDSA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents btnLoadBDSA As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnLoadPortland control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents btnLoadPortland As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnLoadTerregles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents btnLoadTerregles As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btntoCsv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents btntoCsv As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents GridView1 As Global.System.Web.UI.WebControls.GridView

End Class
