<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="headerless_update.aspx.vb" Inherits="admintickets.headerless_update" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
        </div>
    </form>


        <!--Reference the jQuery library. -->
    <script src="Scripts/jquery-3.4.1.min.js" ></script>

    <script src="Scripts/jquery-ui.min.js"></script>
   

        <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.2.2.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>


      <script type="text/javascript">
        
        $(function () {
            // Declare a proxy to reference the hub. 
            var chat = $.connection.chatHubticketco;
            // Create a function that the hub can call to broadcast messages.
            //chat.client.broadcastMessage = function (TotalCheckedIn, WalkUpCheckedIn, OnlineCheckedIn, OnlineSold, SeasonTicketsCheckedIn, AwaySold, HomeSold, awaycheckedin, homecheckedin, BDS1CheckedIn, BDS2CheckedIn, BDS3CheckedIn, BDS4CheckedIn, BDS5CheckedIn, BDS7CheckedIn, BDS8CheckedIn, BDS9CheckedIn, OakbankCheckedIn, TerreglesCheckedIn, Alpha1CheckedIn, Alpha2CheckedIn, Alpha3CheckedIn, Alpha4CheckedIn, AlphaTS1, AlphaTS2, EncTS1, TerraceTS1, BDSTS1, BDSTS2, lastupdate, BDS6CheckedIn, HomeWalkUpCheckedIn, AwayWalkUpCheckedIn, ReportedCrowd, other, CompsCheckedIn, fixturename) {
            //    // Html encode display name and message. 
            //    var TotalCheckedIn = $('<div />').text(TotalCheckedIn).html();
            //    var WalkUpCheckedIn = $('<div />').text(WalkUpCheckedIn).html();
            //    var HomeWalkUpCheckedIn = $('<div />').text(HomeWalkUpCheckedIn).html();
            //    var AwayWalkUpCheckedIn = $('<div />').text(AwayWalkUpCheckedIn).html();

            //    var OnlineCheckedIn = $('<div />').text(OnlineCheckedIn).html();
            //    var OnlineSold = $('<div />').text(OnlineSold).html();
            //    var SeasonTicketsCheckedIn = $('<div />').text(SeasonTicketsCheckedIn).html();
            //    var awaycheckedin = $('<div />').text(awaycheckedin).html();
            //    var homecheckedin = $('<div />').text(homecheckedin).html();
            //    var awaysold = $('<div />').text(AwaySold).html();
            //    var homesold = $('<div />').text(HomeSold).html();
            //    var lastupdate = $('<div />').text(lastupdate).html();
            //    var BDS1CheckedIn = $('<div />').text(BDS1CheckedIn).html();
            //    var BDS2CheckedIn = $('<div />').text(BDS2CheckedIn).html();
            //    var BDS3CheckedIn = $('<div />').text(BDS3CheckedIn).html();
            //    var BDS4CheckedIn = $('<div />').text(BDS4CheckedIn).html();
            //    var BDS5CheckedIn = $('<div />').text(BDS5CheckedIn).html();
            //    var BDS6CheckedIn = $('<div />').text(BDS6CheckedIn).html();
            //    var BDS7CheckedIn = $('<div />').text(BDS7CheckedIn).html();
            //    var BDS8CheckedIn = $('<div />').text(BDS8CheckedIn).html();
            //    var BDS9CheckedIn = $('<div />').text(BDS9CheckedIn).html();
            //    var OakbankCheckedIn = $('<div />').text(OakbankCheckedIn).html();

            //    var TerreglesCheckedIn = $('<div />').text(TerreglesCheckedIn).html();

            //    var Alpha1CheckedIn = $('<div />').text(Alpha1CheckedIn).html();
            //    var Alpha2CheckedIn = $('<div />').text(Alpha2CheckedIn).html();
            //    var Alpha3CheckedIn = $('<div />').text(Alpha3CheckedIn).html();
            //    var Alpha4CheckedIn = $('<div />').text(Alpha4CheckedIn).html();

            //    var AlphaTS1 = $('<div />').text(AlphaTS1).html();
            //    var AlphaTS2 = $('<div />').text(AlphaTS2).html();
            //    var EncTS1 = $('<div />').text(EncTS1).html();
            //    var TerraceTS1 = $('<div />').text(TerraceTS1).html();
            //    var BDSTS1 = $('<div />').text(BDSTS1).html();
            //    var BDSTS2 = $('<div />').text(BDSTS2).html();

            //    var reportedcrowd = $('<div />').text(ReportedCrowd).html();
            //    var other = $('<div />').text(other).html();
            //    var CompsCheckedIn = $('<div />').text(CompsCheckedIn).html();

            //    var homewalkupsold = 0;
            //    var awaywalkupsold = 0;

            //    var totalhomesold = BigInt(homesold) + BigInt(homewalkupsold);
            //    var totalhomecheckedin = BigInt(homecheckedin) + BigInt(HomeWalkUpCheckedIn);

            //    var totalawaysold = BigInt(awaysold) + BigInt(awaywalkupsold);
            //    var totalawaycheckedin = BigInt(awaycheckedin) + BigInt(AwayWalkUpCheckedIn);

            //var fixturename = $('<div />').text(fixturename).html();

        
         
            //};

                
        


            //reconnect connection
            $.connection.hub.disconnected(function () {
                console.log("disconnected");
                setTimeout(function () {
                    $.connection.hub.start();
                }, 5000); // Restart connection after 5 seconds.
                console.log("reconnected");
            });

            $.connection.hub.start().fail(function () {
                console.log("disconnected");
                setTimeout(function () {
                    $.connection.hub.start();
                }, 5000); // Restart connection after 5 seconds.
                console.log("reconnected");
            });


           
            $.connection.hub.start().done(function () {


             //   chat.server.importJSON();

               chat.server.populateDataTable('');
                                 



              
                });

          




           
        });

      </script>


</body>
</html>
