'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Regenerated from markup to restore missing/stale control declarations.
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class standrestricted

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''UCHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents UCHeader As Global.admintickets.UC_header

    '''<summary>
    '''fixturetitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents fixturetitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''PNplan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents PNplan As Global.System.Web.UI.WebControls.panel

    '''<summary>
    '''PNBottomFixed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents PNBottomFixed As Global.System.Web.UI.WebControls.panel

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''PNCard1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents PNCard1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LBCard1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBCard1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TicketID1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents TicketID1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LBCardnm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBCardnm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBCard1Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents TBCard1Name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBCard1email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents TBCard1email As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBCard1address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents TBCard1address As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBCard1postcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents TBCard1postcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DDCard1Type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents DDCard1Type As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDCard1Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents DDCard1Status As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''PNCard2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents PNCard2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LBCard2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBCard2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TicketID2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents TicketID2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBCard2Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents TBCard2Name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBCard2email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents TBCard2email As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBCard2address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents TBCard2address As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBCard2postcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents TBCard2postcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DDCard2Type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents DDCard2Type As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Label5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDCard2Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents DDCard2Status As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''PNCard3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents PNCard3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LBCard3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBCard3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TicketID3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents TicketID3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBCard3Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents TBCard3Name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBCard3email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents TBCard3email As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBCard3address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents TBCard3address As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBCard3postcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents TBCard3postcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DDCard3Type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents DDCard3Type As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Label7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents Label7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDCard3Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents DDCard3Status As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''PNCard4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents PNCard4 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LBCard4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents LBCard4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TicketID4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents TicketID4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents Label8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBCard4Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents TBCard4Name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBCard4email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents TBCard4email As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBCard4address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents TBCard4address As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBCard4postcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents TBCard4postcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DDCard4Type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents DDCard4Type As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Label9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents Label9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDCard4Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents DDCard4Status As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SeasonID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents SeasonID As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Footer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents Footer1 As Global.admintickets.UC_footer

End Class
